### ISSUE TITLE
Collision detection is a little rough

### ISSUE THREAD

**Issue by pcbonnen** [pcbonnen/school-walker#12]
*Requestor*: Andrew Walner

It can be difficult to cut corners because the collision detection will catch the player on corners even though it appears that the player can move at those locations.

**Comment by pcbonnen** [comment]
I would play with the player's collision mask (spr_player_collision_mask) so that it matches the player's feet more closely.

**Comment by beyerb** [comment]
Fixed in commit  4e50364.
