### ISSUE TITLE
Diagonal walking is only enabled in the taco store

### ISSUE THREAD

**Issue by pcbonnen** [pcbonnen/school-walker#17]
*Requestor*: Jonathan Ye

If the player presses two arrow keys simultaneously that suggest diagonal walking, the player does not move diagonally on the town map. However, this same key combination will cause the player to move diagonally while in the taco store.

**Comment by pcbonnen** [comment]
This is probably due to a faulty directional locking mechanism in the player object. Check the arrow key events.

**Comment by rafalogorek** [comment]
Fixed in commit 54ef7c0
