### ISSUE TITLE
"Door is locked" message being displayed when it shouldn't be

### ISSUE THREAD

**Issue by pcbonnen** [pcbonnen/school-walker#2]
*Requestor*: Aaron Tatum

Some houses cause the message "This door is locked" to display even though the player is not near the door.

**Comment by pcbonnen** [comment]
Look at the collision masks for each of the buildings (Under Sprites/buildings/mask) and make sure there aren't any dangling pixels that aren't the door

**Comment by beyerb** [comment]
Fixed in commit 5698194
