### ISSUE TITLE
Blue house glitch

### ISSUE THREAD

**Issue by pcbonnen** [pcbonnen/school-walker#20]
*Requestor*: Lindsey Volta

If the player moves to the right side of the road next to the player's house and moves down towards the blue house, this pushes the blue house down and causes the "Door is locked" message to display, also making the edge of the map appear.

**Comment by pcbonnen** [comment]
This is a very extreme instance of bug #2. There is some noise in the upper-left region of the collision mask for house 2. Check for it and delete it.

**Comment by beyerb** [comment]
Fixed in commit 5698194
