### ISSUE TITLE
Houses go off the edge of the map

### ISSUE THREAD

**Issue by pcbonnen** [pcbonnen/school-walker#23]
*Requestor*: Lindsey Volta

The edges of the game appear to cut off some houses. Indicate the ends of roads so it is more clear to the player where the map ends.

**Comment by rafalogorek** [comment]
We could add some sort of blockade on the road, however, they might get in the way of some buildings' doors. I believe that once the map stops moving with the player, it should become evident to the player that they are reaching the end of the map and don't need a roadblock to indicate that they can't walk any further.
