### ISSUE TITLE
Repeated single tap on arrow keys does not cause player animation

### ISSUE THREAD

**Issue by pcbonnen** [pcbonnen/school-walker#4]
*Requestor*: Aaron Tatum

Repeated tapping on an arrow key makes the player move without showing an animation.

**Comment by pcbonnen** [comment]
This is because we start the animation in the arrow key events but we don't change the subimage. Look at the scripts for these events, and before we set the animation speed, if the animation speed is 0 and we should be moving, set the player's `image_index` to 1. That should fix it.

**Comment by beyerb** [comment]
Fixed in commit ed796cb
