### ISSUE TITLE
Player continues to move if the window loses focus

### ISSUE THREAD

**Issue by pcbonnen** [pcbonnen/school-walker#5]
*Requestor*: Aaron Tatum

If the window loses focus while the player is holding down an arrow key, the character continues to move until the arrow key being held down before is pressed again.

**Comment by pcbonnen** [comment]
Look online for how to detect loss of window focus in GameMaker and write some code to stop the player's movement upon detection of loss of window focus.

**Comment by beyerb** [comment]
For technical reasons, there is no real way to fix this in Game Maker, and it does not significantly affect gameplay, so this bug will not be fixed.
