### ISSUE TITLE
Unable to exit the taco store

### ISSUE THREAD

**Issue by pcbonnen** [pcbonnen/school-walker#8]
*Requestor*: Andrew Walner

If the player approaches the floor mat from the side, the exit does not work and the player is stuck in the taco store.

**Comment by pcbonnen** [comment]
I'm not sure that the player is *stuck* per se...this is probably due to the fact that the player's collision mask is just their feet. To fix this, I'd restrict the movement of the player while in rooms so that the feet cannot go off the bottom of the screen.

**Comment by rafalogorek** [comment]
Fixed in commit 594afae.
