### ISSUE TITLE
Cannot enter pink house

### ISSUE THREAD

**Issue by pcbonnen** [pcbonnen/school-walker#9]
*Requestor*: Andrew Walner

Upon attempting to enter the pink house near the school, the player is not shown the "Door is locked" message, but just walks into an invisible wall.

**Comment by pcbonnen** [comment]
This is probably because the collision map for the town hasn't been updated to allow the player to walk onto the door.

**Comment by rafalogorek** [comment]
Fixed in commit 54ef7c0
